### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by regostar** [Simon-Hohberg/Viola-Jones#12]
Loading faces..
Traceback (most recent call last):
  File "ex.py", line 21, in <module>
    faces_ii_training = list(map(ii.to_integral_image, faces_training))
  File "/home/rego/Documents/Viola-Jones-master/violajones/IntegralImage.py", line 35, in to_integral_image
    integral_image_arr[y+1, x+1] = integral_image_arr[y+1, x-1+1] + row_sum[y, x]
ValueError: setting an array element with a sequence.

**Comment by hadi-goudy** [comment]
need the image to be in grayscale. Probably your images are colored. Use a function to make your images gray scale before using them.
